Resources:
  SupportTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: ${file(./serverless.${opt:stage, self:provider.stage, "dev"}.yaml):supportEmail}
          Protocol: email
